[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = [
  "pnpm install --frozen-lockfile --prod=false"
]

[phases.build]
cmds = [
  "pnpm run build"
]

[phases.start]
cmd = "pnpm start"

[variables]
NODE_ENV = "production"
PORT = "3000"
NIXPACKS_BUILD_CACHE = "false"
