# Docker setup for Java compilation only
# Use this alongside local compilers for other languages

version: "3.8"
services:
  java-compiler:
    image: openjdk:17-jdk-slim
    container_name: codelab-java
    volumes:
      - ./tmp:/workspace
    working_dir: /workspace
    command: tail -f /dev/null # Keep container running
    restart: unless-stopped
    networks:
      - codelab-network

networks:
  codelab-network:
    driver: bridge
